FROM php:fpm-alpine

MAINTAINER Dave Ross dave@davidmichaelross.com

RUN apk update \
    && apk add autoconf  libmemcached \
    && apk add --virtual build-dependencies git g++ gcc make zlib-dev libmemcached-dev cyrus-sasl-dev
RUN docker-php-ext-install mysqli
RUN ln -s /usr/bin/php7 /usr/bin/php \
    && ln -s /usr/bin/php-config7 /usr/bin/php-config \
    && ln -s /usr/bin/phpize7 /usr/bin/phpize
RUN cd /tmp \ 
   && git clone https://github.com/php-memcached-dev/php-memcached.git \
   && cd php-memcached \
   && git checkout php7 \
   && phpize \
   && ./configure --disable-memcached-sasl \
    --includedir=/usr/include --with-libdir=/usr/include --enable-memcached \
   && make \
   && make test \
   && make install
RUN echo extension=memcached.so >> /usr/local/etc/php/conf.d/memcached.ini
RUN echo sendmail_path = /usr/sbin/sendmail -t -i -S mailhog:1025 >> /usr/local/etc/php/conf.d/sendmail.ini
#RUN echo mail.force_extra_parameters = -t -i -S mailhog:1025 >> /usr/local/etc/php/conf.d/sendmail.ini
#RUN echo log_errors = On >> /usr/local/etc/php/conf.d/logs.ini
#RUN echo error_log = /dev/stderr >> /usr/local/etc/php/conf.d/logs.ini
RUN apk del build-dependencies
